ARG version                                              
FROM almalinux:${varsion-9}
ARG course="DevOps with AWS" \
    duration="128hrs"
RUN echo "course: $course, duration: $duration"
CMD ["sleep","100"]