ARG version                                              
FROM almalinux:${varsion-9}
ARG course="DevOps with AWS" \
    duration="128hrs"
ENV duration=$duration
RUN echo "course: $course, duration: $duration, version: $version"
CMD ["sleep","100"]